### PR TITLE
Added Readme File

### PR DESCRIPTION
**Pull request by IConnC**

### CODE REVIEW

**Comment by Caaz** [comment]
Yeah this is probably a good idea. I think this is a decent first pass. Maybe we could set up some steps to get started contributing and stuff.

**Comment by IConnC** [comment]
> Yeah this is probably a good idea. I think this is a decent first pass. Maybe we could set up some steps to get started contributing and stuff.

I've added a bit of contribution guidelines, but I'm not entirely sure exactly what else to add. Any more suggestions to my most recent commits? @Caaz @Zombiefied7

**Comment by IConnC** [comment]
Along with this code request, I suggest implementing GitHub's code review feature to complement the new contribution documentaion. (https://github.com/features/code-review/)

**Comment by IConnC** [comment]
I suggest setting up Issue templates for the repository to complement this PR with the written templates I've proposed. (https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

**Comment by Caaz** [comment]
> > Yeah this is probably a good idea. I think this is a decent first pass. Maybe we could set up some steps to get started contributing and stuff.
> 
> I've added a bit of contribution guidelines, but I'm not entirely sure exactly what else to add. Any more suggestions to my most recent commits? @Caaz @Zombiefied7

🤷 looks good to me, I'd be interested in their comment though. I've got no fancy privileges here. Seems like a good general direction.

**Comment by IConnC** [comment]
@Zombiefied7 What do you think?

**Comment by Zombiefied7** [comment]
I think its really neat that you people are interested in working on this mod. Sure lets have this guideline. not sure that it being so strict is appropriate tho

**Comment by Zombiefied7** [comment]
Its not like there is a huge onslaught of people trying to commit stuff here that we need to filter lol

**Pull request closed without merging**
